Popup window
Shaheryar0054/Portfolio-setup-and-mobile-first pull request #10
Opened 2022-10-21 08:58 UTC by Shaheryar0054

- Added styling for a popup window
- Added javascript functionality
- Added a new javascript file for a popup window
- Added images for a popup window

2022-10-21 12:44 UTC, christianbiring1 requested changes
Hi @Shaheryar0054 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![163947610-e4d849d5-e69c-49b9-90bd-a4191f4e2856](https://user-images.githubusercontent.com/97100091/197198097-70564b24-b15d-4397-a646-69ed45394699.gif)


## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`
- [ ] Great UI :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Populating the data for the exact project where the button was clicked(`image(picture), description`)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-21 12:44 UTC, christianbiring1 commented on index.html
>          </div>
At this stage, Your project is supposed to be rendered dynamically.
- [ ]  Kindly make the projects section is created dynamically with the information from the projects array (_all the HTML of the section is created when the page loads_). `The already created HTML code for the projects list should be removed, and instead, it should be added via JavaScript.`

2022-10-21 12:44 UTC, christianbiring1 commented on style.css
> +
- [ ] Kindly make sure your pop-up model fits the screen size on the Desktop version. It is not supposed to fill all the `height`. As you can see in your design. The user is not even able to see the training part of the model.
Your design :point_down: 

![Screenshot from 2022-10-21 14-28-15](https://user-images.githubusercontent.com/97100091/197197681-c773b2a3-120c-4496-9c1c-be5a0c95ff56.png)

Figma template :point_down: 

![image](https://user-images.githubusercontent.com/97100091/197197759-359c4d20-018d-436c-bca3-ef75f1905788.png)

2022-10-22 10:09 UTC, Abenezer-Tilahun commented on index.html
>          </div>
Fixed.

2022-10-22 10:35 UTC, Abenezer-Tilahun approved these changes
Hi @rozhi-98 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ Professional README  
✔️ Good Commit Messages


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 10:35 UTC, Abenezer-Tilahun commented on style.css
> +}
- [ Optional ] Good job for addressing the previous reviewer suggestion, But  I recommend  to adjust ``margin-left:100px;` to make the popup is responsive, it fits desktop sizes properly.  

Your Project Popup at `margin-left: 171px;` look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/197333974-088a6797-2df5-43d3-b0dc-1e8f8f42bc24.PNG)

I think to fit well at `margin-left: 100px;` Look likes this : 

![Capture](https://user-images.githubusercontent.com/93598189/197334121-69c5339c-1890-4a4a-923c-173030dab514.PNG)

2022-10-22 10:35 UTC, Abenezer-Tilahun commented on style.css
> +  }
- [ optional ] Please make sure that the popup is responsive, it fits mobile  sizes properly. So I recommend you to adjust `margin: 50px 20px;`  to make it responsive.

The Popup for mobile size at `margin: 50px 20px;` look likes this : 

![Capture](https://user-images.githubusercontent.com/93598189/197334515-8441d713-c3f7-4eb2-8ca5-5ed522873ee9.PNG)

2022-10-22 11:13 UTC, merged