Mobile first version
Shaheryar0054/Portfolio-setup-and-mobile-first pull request #4
Opened 2022-09-24 21:21 UTC by Shaheryar0054

**Mobile app design**

- Added HTML and CSS file
- Added background images
- Added google fonts
- Added different section
- Added button hover animation
- uses the flex-box

2022-09-29 07:05 UTC, HAMMAS-SALEEM reviewed
# Invalid Review Request :red_circle: :traffic_light: :rotating_light:

## Salam @Shaheryar0054 :wave: 

**You have made a great effort on your project :blush: and I can see that but unfortunately I can not proceed with a code review of your pull request due to the following reasons :receipt:**

### Once you implement all the changes you should be ready to submit your project for a review :rocket: :rocket:
a
Cheers and Happy coding!👏👏👏

### Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. You can reach out to me on slack by searching my name (Hammas Bin Saleem) for any explanation.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 07:05 UTC, HAMMAS-SALEEM commented on style.css
> +
- [ ] Kindly add an **.gitignore** file in your **project-2** branch :+1: because it is a very important file for all your projects :blush:
- [ ] After adding it, it would be nice if you add **node_modules** at the very first line of **.gitignore** file :thinking: to ignore external dependencies which will just increast the size of your project :thinking:

2022-09-29 10:21 UTC, mckent05 requested changes
Hi @Shaheryar0054, 

# STATUS : CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/193005321-523f648c-5fec-4e5d-b576-dfea0882b7b3.gif)

## Highlights
- Linters are passing ✔️ ✔️ 
- Your repo looks professional 💯 💯 
- Your portfolio is looking really good 👏 👏 

## Required Changes ♻️
- I noticed there is an overflow in your project, please look into fixing this. I have attached an image highlighting the issue


Your project:
![overflow](https://user-images.githubusercontent.com/73607512/193006292-7f79296f-df7a-4cd7-9989-76b4db77574f.PNG)

_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 10:21 UTC, mckent05 commented on index.html
> +    </div>
- Please, I'd suggest that you implement the button interactions such as hover, active, and enabled for each of the project cards 🙏 . This would make for a better user experience 👍 👍 
- For semantic purposes and better accessibility of your site, I'd suggest you use an `article or div` tag to wrap the content of each of your projects and use a `div` tag to wrap all projects aligning them with the `grid` display.  👍 👍

2022-09-29 10:21 UTC, mckent05 commented on index.html
> +<img src="img/Vector 4.png" alt="line" class="bg-vector">
- For better accessibility of your site, I'd suggest placing this as a background image. Please use the CSS `background` property to do this  👍 👍

2022-09-29 11:21 UTC, Shaheryar0054 commented on index.html
> +<img src="img/Vector 4.png" alt="line" class="bg-vector">
okay

2022-09-29 11:43 UTC, 1GORDON requested changes
##
## Hi @Shaheryar0054 ✋  

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions

- [ ] Kindly add all linter files to your root directory. You may add the `.hintrc` and the `.stylelintrc.json` files to your root directory.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 11:43 UTC, 1GORDON commented on index.html
> +                <li class="button-1">bootstrap</li>
Great job @Shaheryar0054 🤝

- [ ] Just like the previous reviewer suggested, kindly put all the cards in an `<article>` or a `<section>` tag and make sure it has a `<display: grid>` on it.
- [ ] Just like the previous reviewer suggested, kindly implement the button interactions across all buttons in your design. At the moment the interactions are implemented only on the first `See Project` button and the `Get My Resume` button.

2022-09-29 12:10 UTC, Shaheryar0054 commented on index.html
> +                <li class="button-1">bootstrap</li>
Please I do not understand can you please be sure to make it more clear for me? I do not understand the cards what is the cards.

2022-09-29 12:39 UTC, 1GORDON commented on index.html
> +                <li class="button-1">bootstrap</li>
Hi @Shaheryar0054 ✋

- [ ] The structure should be something like this.
![cards](https://user-images.githubusercontent.com/63917725/193033529-e4be806b-5bd9-43f7-9cff-4051688dcd0f.PNG)

2022-09-29 16:00 UTC, christianbiring1 requested changes
Hi @Shaheryar0054 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/193080432-292b6cbd-31c5-4f7b-a0c3-dce701bd1566.gif)

 ## Highlights
- [ ] All linters are green
- [ ] Descriptive commits messages
- [ ] Descriptive PR `summary`
- [ ]  Great job for implementing some of the changes as requested by the previous reviewer

 ## Required Changes ♻️
#### Kindly make sure your page is responsive on the mobile screen (width: 320px - 425px)
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 16:00 UTC, christianbiring1 commented on style.css
>  .hambergur-button {
- [x] Kindly make sure you implemented the overflow issues as requested by the previous reviewer. as you can see on mobile how your page is overflowing on the right
![image](https://user-images.githubusercontent.com/97100091/193078432-8bdc31dd-1efa-49d8-91e2-f46de9821977.png)

2022-09-29 16:00 UTC, christianbiring1 commented on index.html
> +            </article>
[OPTIONAL]
- [ ]  You may consider wrapping your tech- stack items inside a `div`  and not an `article` for semantic meaning.
You can find [here](https://www.w3schools.com/tags/tag_article.asp) when to use `article`

2022-09-29 16:00 UTC, christianbiring1 commented on index.html
> +            <img src="img/Rectangle 55.svg" alt="Rectangle" class="language-2">
- [ ] Kindly make sure you implement the changes as requested by the reviewer. these images should.t  to be here. You are supposed to use the background provided in Figma.

2022-09-29 16:11 UTC, Shaheryar0054 commented on style.css
>  .hambergur-button {
Okay, so I need to delete the margin auto property in order to fix that problem?

2022-09-29 17:33 UTC, Shaheryar0054 commented on style.css
>  .hambergur-button {
Please respond to me that how I can fix this error.

2022-09-29 17:35 UTC, Shaheryar0054 commented on style.css
>  .hambergur-button {
Can I use the media query here or not?

2022-09-30 09:20 UTC, Tadesse-Alemayehu approved these changes
Hi @Shaheryar0054 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![approve_happy](https://user-images.githubusercontent.com/69077061/193237253-e7216504-07b6-48ff-a747-bbc23946c9e1.gif)

## Highlights
- All linters are green :heavy_check_mark: 
-  Descriptive commits messages :heavy_check_mark: 
- Descriptive PR summary :heavy_check_mark: 
- Great job for implementing some of the changes as requested by the previous reviewer :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 09:27 UTC, merged